ethereum_rpc = "https://0xrpc.io/hoodi"
drosera_rpc  = "https://relay.hoodi.drosera.io"

eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.mirage_attack]
path = "out/MirageTrap.sol/MirageTrap.json"

# Deployed MirageResponder
response_contract = "0x7ec91278416f2F74Ea11eD1178DA3d895B4D413f"

# MUST exactly match responder ABI
response_function = "respond(int256,uint256)"

block_sample_size = 2
cooldown_period_blocks = 25

min_number_of_operators = 1
max_number_of_operators = 5

private_trap = true
whitelist = [
  "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
]
