name = "Mirage Attack Trap"
description = "Detects abnormal price-liquidity delta (mirage attack signatures)."

ethereum_rpc = "https://0xrpc.io/hoodi"
drosera_rpc  = "https://relay.hoodi.drosera.io"

eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.mirage_attack]
path = "solidity-trap/out/MirageTrap.sol/MirageTrap.json"

# MUST point to the deployed MirageResponder
response_contract = "0xcC76C927347955aEe0e7009A4871d17b38C977bf"

# MUST exactly match the responder signature
response_function = "respond(bytes)"

# Trap logic only reads data[0]
block_sample_size = 1

# Prevent repeated firing while condition persists
cooldown_period_blocks = 20

private_trap = true

# Operator whitelist (example / placeholder)
whitelist = [
  "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
]
