name = "Mirage Attack Trap"
description = "Detects abnormal price-liquidity delta (mirage attack signatures)."

ethereum_rpc = "https://0xrpc.io/hoodi"
drosera_rpc  = "https://relay.hoodi.drosera.io"

eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.mirage_attack]
path = "solidity-trap/out/MirageTrap.sol/MirageTrap.json"

# MUST point to the RESPONDER (Bjorn correction)
response_contract = "0xCc29Ca919b18e2b2b21f13884e78bf03195e47E9"

# MUST match MirageResponder function signature
response_function = "respond(bytes)"

# You only read data[0], so block_sample_size = 1
block_sample_size = 1

cooldown_period_blocks = 0
private_trap = true

# Whitelisted operator (placeholder from Bjornâ€™s example)
whitelist = [
  "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
]
